### PR TITLE
Resampling: label = left

### LINKED ISSUE #180: Resample vs Informative merge
Hi,
first time using github and quite new to python, sorry for any inconvenience.
Resample and informative pairs have different behaviour while merging back to the main dataframe (1m/5m example attached).
I read the explanation of why Informative pair is merged this way (https://github.com/freqtrade/freqtrade/issues/4073) and I think it is correct, but logic seems different for resample. Should not be the same?
I don't get if I am missing something in resample logic.

[Resample_vs_Informative_Merge.xlsx](https://github.com/freqtrade/technical/files/6329498/Resample_vs_Informative_Merge.xlsx)

### PR DESCRIPTION
**Pull request by Masmar25**
Hi!
This PR partially fix resampling logic.
Missing how to manage `resampled_merge` and how to align to `merge_informative_pair` behaviour (main repo).
Probably it will need a PR coordinated with the main repo.

Fixes #180

### CODE REVIEW

**Comment by xmatthias** [comment]
`merge_informative_pair` does not need to be changed, but `resampled_merge` (in this repository) does.

**Comment by Masmar25** [comment]
I agree, I'll change `resampled_merge` so that it behaves the same as `merge_informative_pair`.
This way it will be very similar in code and output to `merge_informative_pair`, so in future probably will be easier to "merge" these two functions (if this is your intention).

PS: this small PR is helping me greatly to understand how Github works. If you think I can make a commit or open a PR in a better way, please correct me. For now I am trying to follow the instructions on the main repo.

**Comment by xmatthias** [comment]
sounds great! :+1: 

> PS: this small PR is helping me greatly to understand how Github works. If you think I can make a commit or open a PR in a better way, please correct me. For now I am trying to follow the instructions on the main repo.

so far, you're doing great! :100: 

should you not know it yet: to update this PR with further changes, simply add your commits to the branch you opened this from and they'll automatically appear here.

**Comment by Masmar25** [comment]
I think it is ready, let me know!
I thought there is a "Ask for Review" button or similar...I cannot see it.

**Comment by Masmar25** [comment]
Thanks! I didn't understand where to read the log of the test for Isort...should I run it on my pc or Github logs it somewhere?
I think I triggered a lot of notifications, not sure if I had to run it locally on my pc or if it is normal.

**Comment by xmatthias** [comment]
it's easier if you run all of the required commands locally (flake8, isort, black) ... but it's also (kindof) fine to let CI let you know about the issues...

**Review by xmatthias — APPROVED** [review]
LGTM :+1:

**Pull request merged**
